/**
 * Frontend API Client Generator
 * Generates API client files in frontend (src/api/*.js)
 */

import fs from 'fs';
import path from 'path';

/**
 * Generate API client files for each resource
 */
export function generateApiClients(projectPath, resources) {
  const apiDir = path.join(projectPath, 'src', 'api');
  
  // Create api directory if it doesn't exist
  if (!fs.existsSync(apiDir)) {
    fs.mkdirSync(apiDir, { recursive: true });
  }

  // Detect if project uses Vite
  const isVite = detectVite(projectPath);

  const generatedFiles = [];

  // Generate a client file for each resource
  for (const resource of resources) {
    const fileName = `${resource.singular}.js`;
    const filePath = path.join(apiDir, fileName);
    
    const clientCode = generateClientCode(resource, isVite);
    fs.writeFileSync(filePath, clientCode, 'utf8');
    
    generatedFiles.push(`src/api/${fileName}`);
  }

  // Generate index.js to export all clients
  const indexPath = path.join(apiDir, 'index.js');
  const indexCode = generateIndexCode(resources);
  fs.writeFileSync(indexPath, indexCode, 'utf8');
  generatedFiles.push('src/api/index.js');

  return generatedFiles;
}

/**
 * Detect if project uses Vite
 */
function detectVite(projectPath) {
  try {
    const packageJsonPath = path.join(projectPath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      const deps = packageJson.dependencies || {};
      const devDeps = packageJson.devDependencies || {};
      
      if (deps.vite || devDeps.vite) {
        return true;
      }
    }
    
    const viteConfigFiles = ['vite.config.js', 'vite.config.ts', 'vite.config.mjs', 'vite.config.cjs'];
    return viteConfigFiles.some((file) => fs.existsSync(path.join(projectPath, file)));
  } catch (error) {
    return false;
  }
}

/**
 * Generate client code for a resource
 */
function generateClientCode(resource, isVite = false) {
  const resourceName = resource.name;
  const singular = resource.singular;
  const capitalizedSingular = capitalize(singular);
  
  const envVar = isVite ? 'import.meta.env.VITE_API_URL' : 'process.env.REACT_APP_API_URL';
  const fallbackUrl = "'http://localhost:5000'";

  return `/**
 * API Client for ${capitalizedSingular}
 * Auto-generated by offbyte
 */

const API_BASE_URL = ${envVar} || ${fallbackUrl};

/**
 * Get all ${resourceName}
 */
export const getAll${capitalize(resourceName)} = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = \`\${API_BASE_URL}/api/${resourceName}\${query ? '?' + query : ''}\`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(\`Failed to fetch ${resourceName}\`);
  }

  return response.json();
};

/**
 * Get single ${singular} by ID
 */
export const get${capitalizedSingular}ById = async (id) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}/\${id}\`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(\`Failed to fetch ${singular}\`);
  }

  return response.json();
};

/**
 * Create new ${singular}
 */
export const create${capitalizedSingular} = async (data) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}\`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(\`Failed to create ${singular}\`);
  }

  return response.json();
};

/**
 * Update ${singular} (partial update)
 */
export const update${capitalizedSingular} = async (id, data) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}/\${id}\`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(\`Failed to update ${singular}\`);
  }

  return response.json();
};

/**
 * Delete ${singular}
 */
export const delete${capitalizedSingular} = async (id) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}/\${id}\`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(\`Failed to delete ${singular}\`);
  }

  return response.json();
};

export default {
  getAll${capitalize(resourceName)},
  get${capitalizedSingular}ById,
  create${capitalizedSingular},
  update${capitalizedSingular},
  delete${capitalizedSingular}
};
`;
}

/**
 * Generate index.js that exports all clients
 */
function generateIndexCode(resources) {
  let code = `/**
 * API Clients Index
 * Auto-generated by offbyte
 */

`;

  // Import all clients
  for (const resource of resources) {
    code += `import ${resource.singular}API from './${resource.singular}.js';\n`;
  }

  code += '\n';

  // Export all
  code += 'export {\n';
  for (const resource of resources) {
    code += `  ${resource.singular}API,\n`;
  }
  code += '};\n\n';

  // Default export
  code += 'export default {\n';
  for (const resource of resources) {
    code += `  ${resource.singular}: ${resource.singular}API,\n`;
  }
  code += '};\n';

  return code;
}

/**
 * Capitalize first letter
 */
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export default { generateApiClients };

