/**
 * Frontend API Client Generator
 * Generates API client files in frontend (src/api/*.js)
 */

import fs from 'fs';
import path from 'path';

/**
 * Generate API client files for each resource
 */
export function generateApiClients(projectPath, resources) {
  const apiDir = path.join(projectPath, 'src', 'api');
  
  // Create api directory if it doesn't exist
  if (!fs.existsSync(apiDir)) {
    fs.mkdirSync(apiDir, { recursive: true });
  }

  const generatedFiles = [];

  // Generate a client file for each resource
  for (const resource of resources) {
    const fileName = `${resource.singular}.js`;
    const filePath = path.join(apiDir, fileName);
    
    const clientCode = generateClientCode(resource);
    fs.writeFileSync(filePath, clientCode, 'utf8');
    
    generatedFiles.push(`src/api/${fileName}`);
  }

  // Generate index.js to export all clients
  const indexPath = path.join(apiDir, 'index.js');
  const indexCode = generateIndexCode(resources);
  fs.writeFileSync(indexPath, indexCode, 'utf8');
  generatedFiles.push('src/api/index.js');

  return generatedFiles;
}

/**
 * Generate client code for a resource
 */
function generateClientCode(resource) {
  const resourceName = resource.name;
  const singular = resource.singular;
  const capitalizedSingular = capitalize(singular);

  return `/**
 * API Client for ${capitalizedSingular}
 * Auto-generated by offbyte
 */

const API_BASE_URL = process.env.REACT_APP_API_URL || process.env.REACT_APP_API_URL;

/**
 * Get all ${resourceName}
 */
export const getAll${capitalize(resourceName)} = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = \`\${API_BASE_URL}/api/${resourceName}\${query ? '?' + query : ''}\`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(\`Failed to fetch ${resourceName}\`);
  }

  return response.json();
};

/**
 * Get single ${singular} by ID
 */
export const get${capitalizedSingular}ById = async (id) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}/\${id}\`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(\`Failed to fetch ${singular}\`);
  }

  return response.json();
};

/**
 * Create new ${singular}
 */
export const create${capitalizedSingular} = async (data) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}\`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(\`Failed to create ${singular}\`);
  }

  return response.json();
};

/**
 * Update ${singular}
 */
export const update${capitalizedSingular} = async (id, data) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}/\${id}\`;
  
  const response = await fetch(url, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(\`Failed to update ${singular}\`);
  }

  return response.json();
};

/**
 * Delete ${singular}
 */
export const delete${capitalizedSingular} = async (id) => {
  const url = \`\${API_BASE_URL}/api/${resourceName}/\${id}\`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(\`Failed to delete ${singular}\`);
  }

  return response.json();
};

export default {
  getAll${capitalize(resourceName)},
  get${capitalizedSingular}ById,
  create${capitalizedSingular},
  update${capitalizedSingular},
  delete${capitalizedSingular}
};
`;
}

/**
 * Generate index.js that exports all clients
 */
function generateIndexCode(resources) {
  let code = `/**
 * API Clients Index
 * Auto-generated by offbyte
 */

`;

  // Import all clients
  for (const resource of resources) {
    code += `import ${resource.singular}API from './${resource.singular}.js';\n`;
  }

  code += '\n';

  // Export all
  code += 'export {\n';
  for (const resource of resources) {
    code += `  ${resource.singular}API,\n`;
  }
  code += '};\n\n';

  // Default export
  code += 'export default {\n';
  for (const resource of resources) {
    code += `  ${resource.singular}: ${resource.singular}API,\n`;
  }
  code += '};\n';

  return code;
}

/**
 * Capitalize first letter
 */
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export default { generateApiClients };

