/**
 * API Clients Index
 * Auto-generated by offbyte
 */

import productAPI from './product.js';
import userAPI from './user.js';

export {
  productAPI,
  userAPI,
};

export default {
  product: productAPI,
  user: userAPI,
};
