/**
 * API Client for Product
 * Auto-generated by offbyte
 */

const API_BASE_URL = process.env.REACT_APP_API_URL || process.env.REACT_APP_API_URL;

/**
 * Get all products
 */
export const getAllProducts = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/products${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch products`);
  }

  return response.json();
};

/**
 * Get single product by ID
 */
export const getProductById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/products/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch product`);
  }

  return response.json();
};

/**
 * Create new product
 */
export const createProduct = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/products`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create product`);
  }

  return response.json();
};

/**
 * Update product
 */
export const updateProduct = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/products/${id}`;
  
  const response = await fetch(url, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update product`);
  }

  return response.json();
};

/**
 * Delete product
 */
export const deleteProduct = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/products/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete product`);
  }

  return response.json();
};

export default {
  getAllProducts,
  getProductById,
  createProduct,
  updateProduct,
  deleteProduct
};
