/**
 * API Client for User
 * Auto-generated by offbyte
 */

const API_BASE_URL = process.env.REACT_APP_API_URL || process.env.REACT_APP_API_URL;

/**
 * Get all users
 */
export const getAllUsers = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/users${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch users`);
  }

  return response.json();
};

/**
 * Get single user by ID
 */
export const getUserById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/users/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch user`);
  }

  return response.json();
};

/**
 * Create new user
 */
export const createUser = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/users`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create user`);
  }

  return response.json();
};

/**
 * Update user
 */
export const updateUser = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/users/${id}`;
  
  const response = await fetch(url, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update user`);
  }

  return response.json();
};

/**
 * Delete user
 */
export const deleteUser = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/users/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete user`);
  }

  return response.json();
};

export default {
  getAllUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser
};
